spring.application.name=urlShortener

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:urlshortener;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Enable H2 Console for local monitoring
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Custom application configuration
app.base-url=http://localhost:8080/
